rvm:
 - 2.3.2
 - 2.2.6
 - ruby-head
cache: bundler
gemfile:
  - gemfiles/Gemfile.rails-2.x
  - gemfiles/Gemfile.rails-3.x
  - Gemfile
notifications:
  recipients:
    - jarmo.p@gmail.com
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1.9
sudo: false
